k3s-io/cluster-api-k3s

samples/nutanix/cluster-template-k3s.yaml
samples/nutanix/nutanix-setup.sh

Add a first working sample for Nutanix CAPI Provider (CAPX)
```
kubectl get nodes
NAME                        STATUS   ROLES                       AGE     VERSION
capx-control-plane-vxvwr   Ready    control-plane,etcd,master   9m41s   v1.24.8+k3s1
capx-mt-0-chfx4            Ready    <none>                      8m15s   v1.24.8+k3s1
capx-mt-0-jsx7z            Ready    <none>                      8m25s   v1.24.8+k3s1
```

Sample for Nutanix CAPI provider

---

samples/aws/k3s-template.yaml

Close #17
tested on an aws cluster

Use TCP healthcheck in control plane LB

---

bootstrap/controllers/kthreesconfig_controller.go

Closes #15
I manually tried to edit the status subresource with the `kubectl edit-status` plugin and I confirm that once the DataSecretAvailable flips, then the Ready condition flips too and the cluster is fully initialized:
```console
$ clusterctl describe cluster k3-test-2
NAME                                                          READY  SEVERITY  REASON  SINCE  MESSAGE
Cluster/k3-test-2                                             True                     143m
├─ClusterInfrastructure - AWSCluster/k3-test-2                True                     5h45m
├─ControlPlane - KThreesControlPlane/k3-test-2-control-plane  True                     143m
│ └─Machine/k3-test-2-control-plane-4s42f                     True                     5h45m
└─Workers
└─MachineDeployment/k3-test-2-md-0 …
```

Mark DataSecretAvailable condition to true when setting dataSecretName

---

samples/aws/k3s-template.yaml

I noticed that networking wasn't working for pods scheduled on the worker node.
k3s uses flannel by default, which implements an overlay network using VXLAN, which uses an UDP port (the port number is documented in https://docs.k3s.io/installation/requirements#networking).
I also noticed that using the aws ccm is incompatible with servicelb (see #20) starting with k3s versions >=1.23.
IIUC how networking is supposed to work here, servicelb is meant as a "low tech" load balancer if you expose the node directly to the public internet. But since in the same we're setting up aws ccm, I _think_ we should also disable servicelb.
---
I tested this with this sample app:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
name: nginx-deployment
spec:
selector:
matchLabels:
app: nginx
replicas: …
```

Fix networking in aws k3s-template

---

bootstrap/config/default/kustomization.yaml
controlplane/config/default/kustomization.yaml

The provider label `cluster.x-k8s.io/provider` is required per cluster api's provider contracts.
Fixes https://github.com/cluster-api-provider-k3s/cluster-api-k3s/issues/28

fix: add missing common provider label

---

pkg/k3s/config.go

Fixes #37 
I left the Go fields to use plural and only changed the json field name to use the singular for uniformity with other `[]string` fields in the same struct:
```
KubeletArgs     []string `json:"kubelet-arg,omitempty"`
KubeProxyArgs   []string `json:"kube-proxy-arg,omitempty"`
```

fix: Use singular in --node-label and --node-taint flags

---

tilt-provider.yaml

The org change brought with it a new ghcr repo, and our tilt config must follow.
---
* fix: update tilt provider image config for org change (03d1bc6)

fix: update tilt provider image config for org change

---

bootstrap/api/v1beta1/kthreesconfig_types.go
bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_kthreesconfigs.yaml
bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_kthreesconfigtemplates.yaml
bootstrap/config/crd/bases/controlplane.cluster.x-k8s.io_kthreescontrolplanes.yaml
pkg/k3s/config.go

i wanted to set some args on k3s using `--kube-scheduler-arg` (see [docs](https://docs.k3s.io/cli/server)) but found that it wasn't exposed. in this PR i believe i have exposed that flag such that it will get plumbed through into the config file pushed onto the control plane hosts. i wasn't sure how to go about testing it so i'm hoping you can give me some pointers, or approve if you know it to be okay.

chore: add kube scheduler server args & plumb through to config

---

bootstrap/api/v1beta1/kthreesconfig_types.go
bootstrap/api/v1beta1/zz_generated.deepcopy.go
bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_kthreesconfigs.yaml
bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_kthreesconfigtemplates.yaml
bootstrap/config/crd/bases/controlplane.cluster.x-k8s.io_kthreescontrolplanes.yaml
bootstrap/config/manager/kustomization.yaml
bootstrap/controllers/kthreesconfig_controller.go
controlplane/config/crd/bases/bootstrap.cluster.x-k8s.io_kthreesconfigs.yaml
controlplane/config/crd/bases/bootstrap.cluster.x-k8s.io_kthreesconfigtemplates.yaml
controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_kthreescontrolplanes.yaml
controlplane/config/manager/kustomization.yaml
pkg/k3s/config.go

The `coud-provider=external` kubelet argument was hardcoded. 
I did implement a flag to explicitly set it. Note that this will change the current behavior, as the default value for this new flag is `false`. If this is not visible, I can reverse the flag to keep the current behavior in place.  
The same flag is also used to disable the embedded cloud controller (since the external one will be used)

Expose flag to explicitly disable cloud-provider=external kubelet argument

---

Makefile
metadata.yaml

Closes #55 
This should enable use with [clusterct](https://cluster-api.sigs.k8s.io/clusterctl/overview.html).  
[Reference](https://cluster-api.sigs.k8s.io/clusterctl/provider-contract#metadata-yaml) for the metadata file.
cat << EOF > $HOME/.cluster-api/clusterctl.yaml
providers:
- name: "k3s"
url: "https://github.com/cluster-api-provider-k3s/cluster-api-k3s/releases/v0.1.7/bootstrap-components.yaml"
type: "BootstrapProvider"
- name: "k3s"
url: "https://github.com/cluster-api-provider-k3s/cluster-api-k3s/releases/v0.1.7/control-plane-components.yaml"
type: "ControlPlaneProvider"
EOF
And init a management cluster with `clusterctl init --control-plane k3s:v0.1.7 --bootstrap k3s:v0.1.7`.

Include metadata.yaml in release

---

.github/workflows/pr.yaml
bootstrap/config/crd/bases/controlplane.cluster.x-k8s.io_kthreescontrolplanes.yaml
controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_kthreescontrolplanes.yaml

in a recent PR i pushed changes that included CRD changes, but i didn't regenerate the manifests.
this PR introduces a check that will fail if the developer forgets to do this.
note that it now runs `make build` on PRs, LMK if this is too much CI compute/cost and i can pare it back to just the generation jobs.

chore: ci check to ensure generation has been run

---

.golangci.yml
bootstrap/controllers/kthreesconfig_controller.go
controlplane/api/v1beta1/condition_consts.go
controlplane/controllers/kthreescontrolplane_controller.go
go.mod
go.sum
pkg/token/token.go
pkg/token/token_test.go

Closes https://github.com/cluster-api-provider-k3s/cluster-api-k3s/issues/70
Closes https://github.com/cluster-api-provider-k3s/cluster-api-k3s/issues/69
Related to #53 
This re-solves one of the problems already solved by https://github.com/cluster-api-provider-k3s/cluster-api-k3s/pull/68, but in a way that will not require ownership to be manually patched for existing clusters. It also moves responsibility for the token to the control plane controller, so that coordination around token creation between different KThreesConfigs is not required.
I've added tests for the token functionality that I moved into `./pkg/token`, and performed the following manual tests:
- Initialize non-HA control plane
- Initialize HA control plane
- Scale out non-HA control plane to be HA
- HA control plane …

fix: move responsibility for managing k3s token to control plane controller

---

pkg/cloudinit/controlplane_init.go
pkg/cloudinit/controlplane_join.go
pkg/cloudinit/worker_join.go

This patch includes the creation of the `/run/cluster-api/bootstrap-success.complete` as documented by the Bootstrap provider [contract](https://cluster-api.sigs.k8s.io/developer/providers/bootstrap.html#sentinel-file)
The reason for the one line is that cloud-init is going to execute all commands in the `runcmd` list, in spite of errors.
So the following would be incorrect, as the ` /run/cluster-api/bootstrap-success.complete` would be created even in case of bootstrap failures.
```yaml
runcmd:
- 'curl -sfL https://get.k3s.io/ | INSTALL_K3S_VERSION=%s sh -s - server'
- 'mkdir -p /run/cluster-api && echo success > /run/cluster-api/bootstrap-success.complete'
```

append /run/cluster-api/bootstrap-success.complete

---

bootstrap/api/v1beta1/kthreesconfig_types.go
bootstrap/controllers/kthreesconfig_controller.go
controlplane/controllers/kthreescontrolplane_controller.go
pkg/secret/certificates.go

This is part of etcd changes mentioned in https://github.com/cluster-api-provider-k3s/cluster-api-k3s/issues/75
To be able to access etcd, mgmt cluster need manage etcd server ca

Deploy etcd CA cert if k3s use embeded etcd

---

controlplane/controllers/kthreescontrolplane_controller.go

fix issue https://github.com/cluster-api-provider-k3s/cluster-api-k3s/issues/85

Fix bug that k3scp ObservedGeneration doesn't change

---

controlplane/main.go

Fixes panic on control plane controller start.
--------
* fix(controlplane): remove 2nd call to ctrl.SetupSignalHandler (7e5f05a)

fix(controlplane): remove 2nd call to ctrl.SetupSignalHandler

---

.github/workflows/pr.yaml
.github/workflows/release.yaml
test/e2e/cluster_upgrade.go
test/e2e/cluster_upgrade_test.go
test/e2e/config/k3s-docker.yaml
test/e2e/data/infrastructure-docker/cluster-template.yaml
test/e2e/helpers.go

* Add two upgrade tests, one for single cp cluster, another for HA cluster
* Modification for cluster-template.yaml
* Decouple kind cluster image version and k3s version (as we do not have k8s binary on kind cluster image)
* Remove `k3s2` in the k3s version string, so that we could choose either `k3s2` or `k3s1`
* Add `cluster.x-k8s.io/deployment-name: worker-md-0` selector as in the upgrade test, it relies on this selector for selecting machines (adding the selector will avoid selecting the controlplane machines)
Based on the local test result, it could upgrade a cluster from `v1.28.6+k3s2` to `v1.28.7+k3s1` by modifying `KThreesControlPlane` and `MachineDeployment`, so [issue 84](https://github.com/k3s-io/cluster-api-k3s/issues/84) might already be fixed.

Add cluster-upgrade e2e tests

---

bootstrap/api/v1beta1/kthreesconfig_types.go
bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_kthreesconfigs.yaml
bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_kthreesconfigtemplates.yaml
bootstrap/config/crd/bases/controlplane.cluster.x-k8s.io_kthreescontrolplanes.yaml
bootstrap/controllers/kthreesconfig_controller.go
controlplane/config/crd/bases/bootstrap.cluster.x-k8s.io_kthreesconfigs.yaml
controlplane/config/crd/bases/bootstrap.cluster.x-k8s.io_kthreesconfigtemplates.yaml
controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_kthreescontrolplanes.yaml
pkg/cloudinit/cloudinit.go
pkg/cloudinit/controlplane_init.go
pkg/cloudinit/controlplane_init_test.go
pkg/cloudinit/controlplane_join.go
pkg/cloudinit/worker_join.go
samples/docker/air-gapped/Dockerfile
samples/docker/air-gapped/README.md
samples/docker/air-gapped/k3s-template.yaml

K3s is supporting air-gapped installations(see [k3s Air-Gap Install](https://docs.k3s.io/installation/airgap)). This PR allowed the user to run CAPI k3s in an air-gapped environment.
**Summary** 
* Add a boolean config `AirGapped` to `KThreesAgentConfig`. If set to `true`, in the cloudinit file, it will use `INSTALL_K3S_SKIP_DOWNLOAD=true INSTALL_K3S_EXEC='server' sh /opt/install.sh` instead of `curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=%s sh -s - server`.
* Small Modification to avoid code duplication:
* Merge `controlPlaneCloudJoin` and `controlPlaneCloudInit`
* Introduce a variable `SentinelFileCommand` (the command echo success to `bootstrap-success.complete`)
* Add `samples/air-gapped/README.md` for guiding the user for airgap install setup, also I use it for validation …

❇️ Support airgap install

---

docs/tilt-setup.md
test/e2e/README.md
test/e2e/data/infrastructure-docker/cluster-template.yaml

This PR add a document for tilt setup, to guide developers for rapid development.
I also slightly modified the e2e template so that this template could be reused as a tilt template. Also, I slightly changed the  wording in e2e doc.

📖 Add a development guide for setting up tilt

---

samples/openstack/k3s-template.yaml
samples/openstack/setup.sh

Hello,
I have tested  the sample script on openstack, recently.
Please find a patch for:
- a small typo in setup.sh script
- use v1beta1 syntax
Thanks

Fix k3s v1beta1 openstack

---

controlplane/controllers/const.go
controlplane/controllers/kthreescontrolplane_controller.go
controlplane/controllers/machine_controller.go
controlplane/controllers/remediation.go
controlplane/controllers/scale.go
controlplane/main.go
pkg/k3s/workload_cluster.go
pkg/k3s/workload_cluster_etcd.go
test/e2e/node_scale_test.go

As we have discussed in #97 , we will remove a node by adding a removal annotation. This PR follows the flow described in case 2 in the original proposal. It will fixed #96 .

Modify node removal logic with removal annotation [Etcd proxy] 

---

bootstrap/config/default/manager_auth_proxy_patch.yaml
controlplane/config/default/manager_auth_proxy_patch.yaml
samples/deployment/bootstrap-k3s/v1.2.2/bootstrap-components.yaml
samples/deployment/control-plane-k3s/v1.2.2/control-plane-components.yaml

Note that `logtostderr` is deprecated, so I removed this flag.
Fixed #102

Bump up kube-rbac-proxy version to v0.16.0

---

bootstrap/controllers/kthreesconfig_controller.go
controlplane/controllers/kthreescontrolplane_controller.go
controlplane/controllers/machine_controller.go
controlplane/controllers/remediation.go
controlplane/controllers/scale.go
pkg/k3s/control_plane.go
pkg/k3s/workload_cluster_etcd.go
pkg/locking/control_plane_init_mutex.go
test/e2e/config/k3s-docker.yaml
test/e2e/data/infrastructure-docker/cluster-template-kcp-remediation.yaml
test/e2e/data/infrastructure-docker/cluster-template-md-remediation.yaml
test/e2e/kcp_remediation_test.go
test/e2e/md_remediation_test.go

* Fix machine health check for controlplane
* fix init lock release logic
* add handling for remediation annotation and status
* modify machine_controller logic to handle scenarios when `machine.Status.NodeRef=nil`
* Add 2 e2e tests:
* kcp_remediation for controlplane remediation
* md_remediation for machine deployment remediation
* Code cleanup
* fix TODO for `reconcileKubeConfig`
Fixed #108

Fix KCP remediation & add machine deployment remediation test

---

bootstrap/api/v1beta1/conversion.go
bootstrap/api/v1beta1/conversion_test.go
bootstrap/api/v1beta1/zz_generated.conversion.go
bootstrap/api/v1beta2/kthreesconfig_types.go
bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_kthreesconfigs.yaml
bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_kthreesconfigtemplates.yaml
controlplane/api/v1beta1/conversion.go
controlplane/api/v1beta1/conversion_test.go
controlplane/api/v1beta1/kthreescontrolplane_types.go
controlplane/api/v1beta2/kthreescontrolplane_types.go
controlplane/api/v1beta2/kthreescontrolplanetemplate_types.go
controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_kthreescontrolplanes.yaml
controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_kthreescontrolplanetemplates.yaml
pkg/k3s/config.go

Apologies for the `cabp3v1` import. I think I accidentally added that in a previous PR, so I took the occasion to clean that up.
This PR Closes https://github.com/k3s-io/cluster-api-k3s/issues/106

Deprecate DisableExternalCloudProvider

---

bootstrap/api/v1beta2/kthreesconfig_webhook.go
bootstrap/api/v1beta2/kthreesconfigtemplate_webhook.go
bootstrap/config/webhook/manifests.yaml
controlplane/api/v1beta2/kthreescontrolplane_webhook.go
controlplane/config/webhook/manifests.yaml

This PR should hopefully address https://github.com/k3s-io/cluster-api-k3s/issues/110
The webhook.Defaulter and webhook.Validator interfaces are deprecated anyway, so they should be updated.

Implement CustomValidator and CustomDefaulter webhook interfaces.

---

controlplane/controllers/kthreescontrolplane_controller.go
pkg/k3s/workload_cluster.go
pkg/k3s/workload_cluster_test.go

This should fix a deadlock scenario with the `controlPlane.Status.Initialized` when the `CloudController` module is disabled and `cloud-provider=external` is set as kubelet arg. 
In this case k3s will **not** set `Nodes.Spec.ProviderID`, which is the expected behavior. 
The CAPI Infrastructure provider should set the ProviderID, but in order to set it, the `controlPlane.Status.Initialized` needs to be true first.
For reference, this is a mirror implementation from the RKE2 provider: https://github.com/rancher-sandbox/cluster-api-provider-rke2/pull/302

Check k3s-serving secret to determine controlPlane.Status.Initialized

---

pkg/machinefilters/machine_filters.go
pkg/machinefilters/machine_filters_test.go

This PR addresses https://github.com/k3s-io/cluster-api-k3s/issues/83, changes to the controlplane spec should trigger a rollout of controlplane machines.
I've tried to mirror the approach used in [kubeadm](https://github.com/kubernetes-sigs/cluster-api/blob/main/controlplane/kubeadm/internal/filters.go#L133) as much as possible while adapting for k3s

feat: Changes to controlplane spec should trigger a rollout

---

controlplane/api/v1beta1/conversion.go
controlplane/api/v1beta1/zz_generated.conversion.go
controlplane/api/v1beta2/kthreescontrolplane_types.go
controlplane/api/v1beta2/kthreescontrolplanetemplate_types.go
controlplane/api/v1beta2/zz_generated.deepcopy.go
controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_kthreescontrolplanes.yaml
controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_kthreescontrolplanetemplates.yaml
pkg/k3s/control_plane.go

This PR changes v1beta2 to use rolloutAfter instead of upgradeAfter for parity with the kubeadm controlplane in cluster-api.
Addresses: https://github.com/k3s-io/cluster-api-k3s/issues/115

feat: Change from upgradeAfter to rolloutAfter in v1beta2 api upgrade

---

controlplane/controllers/kthreescontrolplane_controller.go
pkg/k3s/management_cluster.go
pkg/kubeconfig/kubeconfig.go

* Fix a TODO for rotating kubeconfig secret if it is close to expiring
* When created, kubeconfig secret will be effective for a year. If kubeconfig secret will expired in 180 days, it will get rotated
* Address RestConfig creation failure as `RemoteClusterConnectionError` (same as CAPI)
I have manually verified the cert could be rotated and the rotated secret could still be used to connect to the workload cluster.

Fix a TODO for kubeconfig rotation

---

controlplane/controllers/machine_controller.go

**Bug found**
The cluster cannot be deleted if the user first scale down a cluster, and then delete it. The deletion process got stuck
**Why**
* When the cluster is scaling down, a machine is deleted, with `PreTerminateDeleteHookAnnotationPrefix` set
* Machine controller set the `etcd.k3s.cattle.io/remove` to that node, waiting for the `etcd.k3s.cattle.io/removed-node-name` to be set
* User triggered the deletion to the whole cluster, which deletes other healthy control plane
* Machine controller could not check `etcd.k3s.cattle.io/removed-node-name` annotation, as the whole cluster is down. And it stuck forever, with the machine not deleted
**Fix**
Before machine controller remove an etcd member, it will check if the cluster/cp is already under deletion, or if the removed machine is the …

Fix a bug for etcd removal machine controller [Etcd Proxy]

---

test/e2e/data/infrastructure-docker/clusterclass-k3s.yaml

This PR added `unhealthyConditions` to ClusterClass template. I copied the template from CAPI main, but not realized the feature for optional `unhealthyConditions` is not yet released for CAPI core `v1.7.2` (which we used to for e2e). I have tested #124 , but that time I accidentally used a CAPI core build from main branch, so did not find this bug.

Fix a bug for ClusterClass e2e template [e2e test] 

---

controlplane/config/manager/manager.yaml

We are setting a resource limit that is too small for controlplane controller. This results in the controlplane controller crashed frequently. I think we forget to remove it when creating from kubebuilder template. Remove the limit (bootstrap controller also has no limit).

fix: Remove resource limit for controlplane controller [v0.2.0]

---

controlplane/controllers/const.go
controlplane/controllers/kthreescontrolplane_controller.go
controlplane/controllers/machine_controller.go

We did not set a requeue time for etcd proxy machine controller, so the request will be requeued immediately. This triggered lots of requeue, which results the requeue time hits the rate limter upper limit (~`16.67m` which is too long for deletion). As the time between CAPI initialize the etcd removal request to the etcd member is actually removed, it might take ~ 1min. Add a requeue time of 30s so the controller will wait for a while until it pinging the api server again.

fix: Set requeue time for etcd proxy [etcd proxy][v0.2.0]

---

bootstrap/api/v1beta1/conversion.go
bootstrap/api/v1beta1/zz_generated.conversion.go
bootstrap/api/v1beta2/kthreesconfig_types.go
bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_kthreesconfigs.yaml
bootstrap/config/crd/bases/bootstrap.cluster.x-k8s.io_kthreesconfigtemplates.yaml
controlplane/api/v1beta1/conversion.go
controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_kthreescontrolplanes.yaml
controlplane/config/crd/bases/controlplane.cluster.x-k8s.io_kthreescontrolplanetemplates.yaml
pkg/k3s/config.go

Add `systemDefaultRegistry`, it will allow defining private registry to be used for all system images for k3s

Add system-default-registry setting

---

metadata.yaml

Add the missing release series to the metadata so that the v0.2.0 release is installable from clusterctl.

fix: metadata add release series

---

.golangci.yml
controlplane/controllers/const.go
controlplane/controllers/kthreescontrolplane_controller.go
controlplane/controllers/scale.go
go.mod
pkg/k3s/control_plane.go
pkg/util/contract/types.go
pkg/util/hash/hash.go
pkg/util/ssa/cache.go
pkg/util/ssa/doc.go
pkg/util/ssa/filterintent.go
pkg/util/ssa/managedfields.go
pkg/util/ssa/matchers.go
pkg/util/ssa/patch.go
test/e2e/config/k3s-docker.yaml
test/e2e/e2e_suite_test.go
test/e2e/helpers.go
test/e2e/inplace_rollout_test.go

This PR supports ssa patch for capi k3s. With it, the mutable fields on KThreesControlPlane will be propagated to the underlying machines/infrastructureMachine/kthreesconfigs without rollout. Fixed #134
SSA ([Server-Side Apply](https://kubernetes.io/docs/reference/using-api/server-side-apply/)) is needed so that if a label is deleted in KThreesControlPlane, it will also get cleaned up from the underlying resources.

feat: Support SSA patch for metadata propagation

---

test/e2e/README.md
test/e2e/clusterctl_upgrade_test.go
test/e2e/common.go
test/e2e/config/k3s-docker.yaml
test/e2e/data/infrastructure-docker/bases/cluster-with-topology.yaml
test/e2e/data/shared/k3s/v0.2/metadata.yaml
test/e2e/data/shared/v1beta1/metadata.yaml
test/e2e/inplace_rollout_test.go

* Add a new e2e test `clusterctl_upgrade_test` to testing upgrading from v0.2.0 to current version (built from source)
* In complement to `inplace_rollout_test`, the `clusterctl_upgrade_test` will also include scenarios for modifying cluster labels/ annotations after upgrade, to verify SSA patch (#136 ) is working as expected if user upgrade from an old version k3s CAPI.
* Running e2e with tilt is broken (as I need to remove `v1.8.99` from e2e setting, otherwise `clusterctl_upgrade_test` is not functioning), remove that part in e2e README. 
* Fix comment in `inplace_rollout_test`.

test: Add clusterctl upgrade e2e test

---

.github/workflows/e2e-pr.yaml

This PR add a PR blocker with e2e. For now, it will build the repo and verifying by creating a cluster with 1 CP and 3 worker nodes. I mainly follow [rke2 setup](https://github.com/rancher-sandbox/cluster-api-provider-rke2/blob/main/.github/workflows/e2e.yml) and a successful run could be found [here](https://github.com/nasusoba/cluster-api-k3s/actions/runs/9122826401/job/25084256460).
If we want to add other test specs as a PR Blocker, we could simply add `[PR-Blocking]` in its spec name. 
#25

Add a github workflow to enable e2e for PR blocker
